{% set version = "0.3.4" %}

package:
  name: u3d
  version: {{ version }}

source:
  fn: u3d-v{{ version }}.tar.gz
  url: https://github.com/ClinicalGraphics/u3d/archive/{{ version }}.tar.gz
  md5: 415a7255fb033959af1cccf9713e9b7e

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0

requirements:
  build:
  - python  # [win]
  - cmake
  - jpeg 9*
  - libpng >=1.6.28,<1.7
  - zlib 1.2.*
  run:
  - jpeg 9*
  - libpng >=1.6.28,<1.7
  - zlib 1.2.*

test:
  requires:
  - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
  # generate a test.idtf file. this tool never exit code 0 so we force it
  - IDTFGen || true  # [not win]
  - IDTFGen || ver>nul  # [win]
  # then try to generate a u3d file. this tool only exits 0 if it succeeds
  - IDTFConverter -input test.idtf -output test.u3d -debuglevel 0

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: Universal 3D Sample Software
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
    - EelcoHoogendoorn
