{% set version = "0.3.5" %}

package:
  name: u3d
  version: {{ version }}

source:
  url: https://github.com/ClinicalGraphics/u3d/archive/{{ version }}.tar.gz
  md5: 9f3f63422e0efa772b8bf5a774061170

build:
  number: 3

requirements:
  build:
  - {{ compiler('cxx') }}
  - {{ compiler('c') }}
  - cmake
  - make  # [unix]
  host:
  - libjpeg-turbo
  - libpng
  - zlib

test:
  commands:
  # generate a test.idtf file. this tool never exit code 0 so we force it
  - IDTFGen || true  # [not win]
  - IDTFGen || ver>nul  # [win]
  # then try to generate a u3d file. this tool only exits 0 if it succeeds
  - IDTFConverter -input test.idtf -output test.u3d -debuglevel 0

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Universal 3D Sample Software
  
extra:
  recipe-maintainers:
    - Maxyme
    - EelcoHoogendoorn
