travis:
  secure:
    BINSTAR_TOKEN: Svugi669c/kbmHjEhbnP6bkgbqIADe2mHRHRU1oesxOpu2+ebp79GLu4yM1oH4UDmpmAlDaxvL9Twag/7cy+pSICg58uRAxU58Q0jwntwT0Kz4Raw5SB3Qf+oquFnRpSUqcGAX2u5nV41nesUHkY+OmGjnCufvTYB9dQfQ1c/BQ+JygYrmOIAd4YiGxBm9kwGZyeiAacIxEhhoreuk2kAuP1pF61ifqY+1VfBNARZecnDM14M51SoIk9SEt0uJ8397sLmHsI3iE8Al3tQGNKCm4zQp9+FZsaHxFiQW9qJQ+RbzuAp+twqmrovrcoRKf7nP2bN2NpRvqQbpNjFfuJ7nEAGZ3PrLeXNZwb330sN5kUh4bNKFPheA+AR/GszuoyUwncIpRjneapuPMFl5oALVwqrpJCiQYRa8ADi/DNlvX7WQLXRgbzApE1DSYBUZ3sBojYEhabRu4Qa6AMzUzoVeA7W1LpfZC1NlM9e/4WAjxYDybrCPCwgb6SjOr88F26tSj8oyr+PeXg7jzAmjvBGZFqJOOtzPqTHwtRVtFRb31D9AmEp++0KELMK6PlQ+8aUrjkfDLob1jP90roSIbCn0PyPkmveouq+psmF6gU1j8FsgbVdz7UUrKsvfuA0yFhOBtXBbNcQQA8a6vg7vTQOc2NwikmGOZFKggFyPdPdXo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
